### ISSUE TITLE
unable to load [Requirement Structure] Form : Error With ActiveX Objects.

### ISSUE THREAD

**Issue by FlexurAniketrry** [ArasLabs/requirements-management#1]
I have imported the package on Aras11 SP9 , below related item tabs are not working. 

1. Requirement Structure
 >> ActiveX Object Error , 
2. Related Part 
 >> Event handler failed with message: TypeError: top.frames[1].document.thisItem
3. Where Used. 
>> Event handler failed with message: TypeError: top.frames[1].document.thisItem

I am not sure what need to do so it will work for the Aras 11 SP9.

-Aniket Gujrathi
aniketrgujrathi@gmail.com

**Comment by EliJDonahue** [comment]
Hi Aniket,

This project has been archived because it relies on ActiveX controls, which are not supported by modern browsers. It is not possible to upgrade the project to support Aras 11 SP9 due to current browser technology. If you are interested in a requirements management solution, I recommend checking out the Aras Requirements Management application.

If you would like to learn more about the Aras Requirements Management application, I recommend contacting the Aras Community team at info@aras.com. You can also check out the demo videos available on the Aras website: 

http://www.aras.com/resources/?topic=Requirements-Management&industry=&type=Demo
